[build]
  publish = "website"
  
# Security Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; script-src 'self' 'unsafe-inline'"

# Cache Headers for Performance
[[headers]]
  for = "/styles.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/script.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/favicon.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects for SEO and User Experience
[[redirects]]
  from = "/signup"
  to = "/#membership"
  status = 301

[[redirects]]
  from = "/join"
  to = "/#membership"  
  status = 301

[[redirects]]
  from = "/pricing"
  to = "/#membership"
  status = 301

[[redirects]]
  from = "/workouts"
  to = "/#sports"
  status = 301

[[redirects]]
  from = "/sports"
  to = "/#sports"
  status = 301

[[redirects]]
  from = "/ai"
  to = "/#ai-features"
  status = 301

# Form Processing
[form]
  settings = true

# Environment Variables (for future use)
[context.production.environment]
  NODE_ENV = "production"
  SITE_URL = "https://fitfriendsclubs.com"