#!/bin/bash

# Cloudflare Email Routing Quick Setup for fitfriendsclub.com
# This script provides the steps to configure email routing via Cloudflare Dashboard

echo "==================================================="
echo "Cloudflare Email Routing Setup for fitfriendsclub.com"  
echo "==================================================="
echo ""

echo "📧 STEP 1: Enable Email Routing in Cloudflare"
echo "----------------------------------------------"
echo "1. Go to: https://dash.cloudflare.com"
echo "2. Select domain: fitfriendsclub.com" 
echo "3. Navigate to: Email → Email Routing"
echo "4. Click: 'Enable Email Routing'"
echo ""

echo "📨 STEP 2: Add Custom Email Addresses"
echo "------------------------------------"
echo "Add these custom addresses in Cloudflare Email Routing:"
echo ""
echo "• hello@fitfriendsclub.com → [YOUR-PERSONAL-EMAIL]"
echo "• support@fitfriendsclub.com → [YOUR-SUPPORT-EMAIL]" 
echo ""
echo "Replace [YOUR-PERSONAL-EMAIL] with your actual Gmail/email address"
echo ""

echo "🔧 STEP 3: Verify DNS Records (Automatic)"
echo "---------------------------------------"
echo "Cloudflare will automatically add these MX records:"
echo ""
echo "• isaac.mx.cloudflare.net (Priority: 46)"
echo "• linda.mx.cloudflare.net (Priority: 92)"  
echo "• amir.mx.cloudflare.net (Priority: 78)"
echo ""

echo "📋 STEP 4: Verify SPF Record"
echo "---------------------------"
echo "Cloudflare should add this TXT record automatically:"
echo "v=spf1 include:_spf.mx.cloudflare.net ~all"
echo ""

echo "✅ STEP 5: Test Email Configuration"
echo "---------------------------------"
echo "After setup (may take 5-10 minutes):"
echo ""

# Check current MX records
echo "Current MX records for fitfriendsclub.com:"
dig fitfriendsclub.com MX +short 2>/dev/null || echo "No MX records found yet"
echo ""

echo "🔄 STEP 6: Testing Commands"
echo "-------------------------"
echo "Run these commands to verify setup:"
echo ""
echo "# Check MX records:"
echo "dig fitfriendsclub.com MX"
echo ""
echo "# Check SPF record:"  
echo "dig fitfriendsclub.com TXT | grep spf"
echo ""
echo "# Test email delivery:"
echo "Send a test email to: hello@fitfriendsclub.com"
echo ""

echo "💡 BENEFITS OF CLOUDFLARE EMAIL ROUTING:"
echo "---------------------------------------"
echo "✓ Completely FREE"
echo "✓ No monthly fees"
echo "✓ Instant setup via Cloudflare dashboard"
echo "✓ Automatic DNS configuration"
echo "✓ Professional email addresses"
echo "✓ Email forwarding to existing accounts"
echo ""

echo "🚀 ALTERNATIVE: Google Workspace (Full Email Hosting)"
echo "---------------------------------------------------"
echo "If you need full email accounts (not just forwarding):"
echo "• Cost: $6/user/month"
echo "• Full Gmail interface"
echo "• Calendar, Drive, Meet included"
echo "• Setup guide in EMAIL_HOSTING_SETUP.md"
echo ""

echo "📞 CONTACT FORM INTEGRATION"
echo "-------------------------"
echo "Your website contact form is already configured to use:"
echo "• hello@fitfriendsclub.com (main contact)"
echo "• support@fitfriendsclub.com (support inquiries)"
echo ""
echo "Once email routing is active, form submissions will be"
echo "forwarded to your configured destination addresses."
echo ""

echo "==================================================="
echo "Setup complete! Check EMAIL_HOSTING_SETUP.md for detailed instructions."
echo "==================================================="