# FitFriendsClubs API - Cloudflare Worker Configuration
name = "fitfriendsclubs-api"
main = "cloudflare-worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

# Production environment with custom domain routing
[env.production]
routes = [
  { pattern = "api.fitfriendsclubs.com/*", zone_name = "fitfriendsclubs.com" }
]

# Environment variables
[env.production.vars]
ENVIRONMENT = "production"
API_VERSION = "1.0"

# R2 Storage for image uploads
[[env.production.r2_buckets]]
binding = "IMAGES_BUCKET"
bucket_name = "fitfriendsclubs-images"

# Development environment for testing
[env.development]
# Local development configuration

# Secrets to set via CLI:
# wrangler secret put DATABASE_API_URL --env production
# wrangler secret put DATABASE_API_KEY --env production

# KV Storage for caching (optional)
[[kv_namespaces]]
binding = "CACHE"
id = "your-kv-namespace-id"

# Custom domains (configure in Cloudflare dashboard)
[routes]
pattern = "api.fitfriendsclub.com/*"
zone_name = "fitfriendsclub.com"