# FitFriendsClubs API - Cloudflare Worker Configuration
name = "fitfriendsclubs-api"
main = "cloudflare-worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

# Production environment with custom domain routing
[env.production]
routes = [
  { pattern = "api.fitfriendsclubs.com/*", zone_name = "fitfriendsclubs.com" }
]

# Environment variables
[env.production.vars]
ENVIRONMENT = "production"
API_VERSION = "1.0"
# Supabase configuration (non-sensitive values)
# Replace SUPABASE_ANON_KEY with your actual anon key from Supabase Dashboard → Settings → API
SUPABASE_URL = "https://bkaebhccbzpwiyxmpyln.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJrYWViaGNjYnpwd2l5eG1weWxuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzMjk2NDQsImV4cCI6MjA3NDkwNTY0NH0.n_PZ5YsBxjF6jDPM3HPZ5Vl3ilgKfHiHRVoiLM1h5nY"

# R2 Storage for image uploads
[[env.production.r2_buckets]]
binding = "IMAGES_BUCKET"
bucket_name = "fitfriendsclubs-images"

# Development environment for testing
[env.development]
# Local development configuration

# Secrets to set via CLI:
# wrangler secret put SUPABASE_SERVICE_KEY --env production
# wrangler secret put DATABASE_URL --env production
# wrangler secret put TURN_SERVER_SECRET --env production
# KV Storage for caching (optional - comment out if not using)
# [[kv_namespaces]]
# binding = "CACHE"
# id = "your-kv-namespace-id"

# Custom domains (configure in Cloudflare dashboard)
# [routes]
# pattern = "api.fitfriendsclub.com/*"
# zone_name = "fitfriendsclub.com"